transientskp/pyse

- .gitignore
- .travis.yml
- gitlistobjectbysize.sh
- nosetests_from_command_line.sh
- sourcefinder/image.py
- sourcefinder/stats.py
- test/data/pointer_files/GRB120422A-120429.fits
- test/data/pointer_files/NCP_sample_image_1.fits
- test/data/pointer_files/SWIFT_554620-130504.fits
- test/data/pointer_files/corrected-all.fits
- test/data/pointer_files/correlated_noise.fits
- test/data/pointer_files/deconvolved.fits
- test/data/pointer_files/model-all.fits
- test/data/pointer_files/observed-all.fits
- test/data/pointer_files/uncorrelated_noise.fits
- test/test_FDR.py
- test/test_image.py
Fixes #7 
However, it involves quite an overhaul of stats.sigma_clip.
In summary, what I ran into with an artificial 4K * 4K image with 167000 sources of ~ 100 Jy on top of Gaussian noise with an std of 1 Jy is that no clipping was done at all, because the initial estimate of the std - so before any clipping- of the background noise was so high: over 19 Jy.
The dynamical clipping limit related to equation 2.22 of my thesis set kappa equal to about five, I believe, and all pixels were below that limit of kappa * 19 Jy.
Now the dynamical clipping limit ensures that any parameters derived from the clipped distribution are not biased by clipping. 
No bias is good, so when dropping the dynamical clipping limit something else is needed to correct for the clipping bias.
I could do that by …
> Fix no clipping when source density is high

- sourcefinder/extract.py
- sourcefinder/fitting.py
Fixes #9 
This just adds some condtionals for the case that `xxbar==yybar` in [fitting.py](https://github.com/transientskp/pyse/blob/a8310c2967bf597d265376e7e5bd8ca598bb34be/sourcefinder/fitting.py#L96) to avoid a division by zero and a nan check for `self.theta_dc.value` in [extract.py](https://github.com/transientskp/pyse/blob/a8310c2967bf597d265376e7e5bd8ca598bb34be/sourcefinder/extract.py#L950).
In this way the nosetests can be run without warnings.
> Fix runtimewarnings from nosetests.

- sourcefinder/image.py
`scipy.ndimage.map_coordinates` is used to interpolate the grid values of the background mode and rms to the entire image.
Default this is done using bilinear interpolation.
For that case much faster solutions are available.
One of the answers to this [SO question](https://stackoverflow.com/questions/13242382/resampling-a-numpy-array-representing-an-image) includes these four lines of code:
```
f = interp.interp1d(y, im, kind='linear')
temp = f(new_y)
f = interp.interp1d(x, temp.T, kind='linear')
new_im = f(new_x).T
```
This is more than three times faster than `scipy.ndimage.map_coordinates` for linear interpolation. 
`scipy.ndimage.zoom` should also be an option for speedup, but even after extensive tweaking of the `zoom` parameters I could not produce the exact same output as …
> Faster interpolation than scipy.ndimage.map_coordinates for the linear case.

- scripts/pyse
- sourcefinder/image.py
Originally intended as a branch to make connected component labeling (ccl) run faster using the pyvips/libvips library.
Then it turned out that segmentation (thresholding) was way more computationally expensive than ccl.
And more than half of the time to perform the segmentation was devoted to computing a median of the noisemap, i.e. a median over the entire image. Way too expensive and does not make sense, since these are mostly interpolated values. Why include them in computing the median? Now we use only the grid values, which is much faster.
> Accelerate label islands

- nosetests_from_command_line.sh
- sourcefinder/image.py
For some unit tests, grid.shape=(1,1) and then `interp1d` from `scipy.interpolate` will break with "ValueError: x and y arrays must have at least 2 entries". So in that case `map_coordinates` should be used.
> Unit tests failed because of grid.shape=(1,1) for a number of these tests.

- .gitignore
- Dockerfile
- nosetests_from_command_line.sh
- scripts/pyse
- sourcefinder/image.py
This implements paralllellisation of kappa, sigma clipping in PySE using Dask. 
The output is numerically equal to the output from the Ray implementation, which is numerically equal to the output of the single threaded implementation of the `Fix-no-clipping-when-source-density-is-high` branch.
For the optimum workload per thread, the Dask implementation completed clipping in 2.0s on my laptop. For the Ray implementation it took 3.0s.
However, on my more powerful pc the relative difference became somewhat smaller.
> Kappa sigma clipping using dask

- sourcefinder/image.py
This parallellisation of the fitting of sources should be the last part of the parallellisation of pyse.
This does not mean that it is as fast as it could be.
That would require translation of some routines to C-libraries.
But I think all the low-hanging fruit wrt straightforward parallellisation has been picked with this last merge.
> Parallel fitting

- sourcefinder/extract.py
- sourcefinder/fitting.py
- sourcefinder/image.py
- sourcefinder/stats.py
- test/test_errors.py
- test/test_gaussian.py
This branch was created to bypass repeated calculations of `fudge_max_pix`, `max_pix_variance`, `beamsize` and `correlation_lengths`, by adding them as an argument to the `fit` method to the `extract.Island` objects, instead of repeatedly calculating these same quantities for each island. 
Also the unit tests have been adapted to the new interfaces to e.g. `source_profile_and_errors`. 
I have mixed feelings about the commits in this branch. Yes, I achieved a considerable (~33%) speedup in `_pyse`. But I could have perhaps achieved the same speedups by using something like the `Memoize` or `functools.cache` decorator to e.g. `fudge_max_pix`. This would have required less of a code overhaul. 
And `calculate_correlation_lenths` and `calculate_beamsize` are lightweight anyway. 
After this …
> Fudge max pix and maximum pixel method variance should only be called once per image

- scripts/pyse
- sourcefinder/image.py
- test/test_image.py
- test/test_source_measurements.py
`sep.extract` turns out to be able to do connected component labelling (ccl) quite fast. 
We can, however, not use 4-connectivity or an arbitrary structuring element.
8-connectivity is set in stone in `SExtractor` hence in `sep`.
`sep.extract` does more than ccl, it also does source measurements, albeit without the accuracy of (Gaussian) fits - it uses the `moments` or `barycenter` method, that is also implemented in `PySE`, but in `PySE` as an initial 'guess' to start Gauss fitting.
We don't use these source measurements from `sep.extract` yet, just the segmented islands, the rest of `PySE` still uses its own routines for source measurements.
The next step could be to speed up those source measurements using e.g. Numba ot to use the source measurements from `sep.extract`. The latter …
> Connected component labeling using sep

- sourcefinder/extract.py
- sourcefinder/image.py
Did lots of timing of functions. I noticed that timing from bash includes launching the Python interpreter which takes 0.8s. Will exclude that and do a %timeit %run pyse.py --detection=10 --analysis=10 --grid=128 --bmaj=0.001414711 --bmin=0.001111111 --bpa=0 FITS_files/SOURCESINSERTED_2230_2230.FITS from the iPython prompt from now on. I noticed that loading the FITS image and header takes about 40 ms. Computing background characteristics takes about 130 ms. These are pretty much optimized. Also applying numba.jit decorators to anything within extract.py either does not work because the function is too complicated for Numba or gives negligible speedup. The core of fitting is a scipy.optimize.leastsq which is already pretty optimized, but still a lot slower than computing source profiles …
> Commented out Gauss fitting

- sourcefinder/extract.py
- sourcefinder/image.py
This branch was created to make use of processes for multiprocessing twice, for two methods, since creating processes is expensive, it takes 0.6-0.7s. The processes would already created for the fitting loop, but if we were to create them earlier, such that they can already be used for the post labelling loop (and keeping them for parallel fitting such that they do not have to recreated), we would achieve a speedup. This, however, completely failed. We started off by creating a multiprocessing Pool that we fed with the labels to a static method created to do the post labelling work. That took 10s, so way longer than before, probably because a number of maps had to be duplicated. As an instantiation method, this took forever and we had to kill the process. 
So why does the parallellisation …
> Original plan for speedup did not work out, but some PEP formatting changes remain

- sourcefinder/extract.py
Adding the `.abc` should suffice.
So now we have
`from collections.abc import MutableMapping`.
Fixes #35
> This should enable a correct import of MutableMapping.

- scripts/pyse
- setup.py
This was missing, as noticed by @dentalfloss1.
Fixes #36 
Only `dask.array` is needed, since we are only using `dask.array. map_blocks`, in `sourcefinder/image.py`.
`dask.distributed` was used in `scripts/pyse`, but seems redundant, so has been removed.
`psutil` has also been added to `setup.py`, it is needed to count the number of (logical) cores in `sourcefinder/image.py`, for `multiprocessing` through `pool.map`.
> Add dask to setup

- sourcefinder/utility/coordinates.py
Python 3 does not know the `cmp` function. 
Apparently that was still part of this repo, i.e. in line 347 of `sourcefinder/utility/coordinates.py`, in the `angsep` function.
In the tkp repo this has been corrected.
The solution, as usual, comes from [SO](https://stackoverflow.com/questions/22490366/how-to-use-cmp-in-python-3): simply add a `cmp` function.
This also fixes #6 in the sense that, using this branch, an AARTFAAC image could be correctly processed with a "Numpy version greater than 1.10.x". 
1.24.1 in this case.
> Added cmp function 

- sourcefinder/image.py
- test/test_image.py
`extract`, as called from `reverse_se`, needs `anl` as a second positional argument.
This means that `anl` should be an argument of `reverse_se`. 
Also, `reverse_se` had not been tested, so a unit test is added. 
This takes a 2K * 2K image and should extract no sources when using `reverse_se` at the 5 sigma level.
Fixes #51
> extract, as called from reverse_se, needs anl as a second positional argument.

- sourcefinder/extract.py
- sourcefinder/image.py
- test/test_image.py
This commit involves considerable changes in computing moments for 'thin' islands, triggered by a logger warning, from line 1117 in image.py when processing an AARTFAAC TBB image from an infinite error in declination: 'Bad fit from blind extraction at pixel coords'. 
This was caused by computing moments for 'thin' islands in the same way as for 'thick' islands. This yielded an extreme small semi-minor axis (~1e-8 in pixel coordinates). When such an unrealistically small semi-minor axis is propagated into the error analysis, the end of the declination error bar can be outside the image. In that case wcsp2s can give 'inf'.
To fix this one has to reconsider computing moments for thin islands: it does not make sense to compute these if the minimal width is 1, as in the above cases. Actually, …
> Compute moments for thin islands differently

- sourcefinder/extract.py
- sourcefinder/fitting.py
- sourcefinder/image.py
- sourcefinder/stats.py
- sourcefinder/utility/containers.py
- sourcefinder/utility/coordinates.py
- sourcefinder/utils.py
- test/test_L15_12h_const.py
> Produce all required quantities for vectorized source measurements

- sourcefinder/image.py
- sourcefinder/utils.py
Fixes #67 
Fixes #88 
The problem is well described as part of that second issue.
In summary: previously masks were not fully accounted for in calculating the background characteristics.
After [commit 3a7919a](https://github.com/transientskp/pyse/pull/87/commits/3a7919aa78642fbcc1fba4b716d1db36130421f9) this was fixed, but subsequently the masks of (partially) masked subimages - centered on grid nodes - were not fully accounted for or led to `RuntimeWarning: invalid value encountered in scalar divide`.
Grid node values centered on (partially) masked subimages are now first set to zero and then replaced by its nearest nonzero neighbour. 
This means that `rms_grid` and `mode_grid` do not have a mask, they are regular Numpy ndarrays.
That is a better way of working since …
> Fix flaw in bg calculation

- sourcefinder/extract.py
- sourcefinder/fitting.py
- sourcefinder/image.py
- sourcefinder/utils.py
- test/test_errors.py
- test/test_gaussian.py
- test/test_image.py
- test/test_sf_utils.py
> Fix 105 and 118

- sourcefinder/config.py
- sourcefinder/image.py
Addresses https://github.com/transientskp/pyse/issues/144
> Use back-size-x/y if set, fall back to grid parameter from config.

- sourcefinder/utils.py
It seems there should be no warnings left, also not when I enable `@njit(parallel=True) ` again it seems to be fine, let's see what the cicd does
> Re-enable parallel make_subimages

- .github/workflows/python-tests.yml
- README.rst
- pyproject.toml
- test/test_L15_12h_const.py
- test/test_image.py
- test/test_scripts/test_pyse.py
- enable test matrices in pyproject.toml
- tests: remove redundant runs for faster CLI tests
- tests: move common test setup to setUpClass
Almost halve test run time by removing redundant test setups that were
expensive.
> Reduce test runtime by ~45%

- docs/source/conf.py
- docs/source/index.rst
- pyproject.toml
- sourcefinder/accessors/aartfaaccasaimage.py
- sourcefinder/accessors/dataaccessor.py
- sourcefinder/accessors/fitsimage.py
- sourcefinder/config.py
- sourcefinder/deconv.py
- sourcefinder/extract.py
- sourcefinder/gaussian.py
- sourcefinder/image.py
- sourcefinder/measuring.py
- sourcefinder/testutil/decorators.py
- sourcefinder/utility/containers.py
- sourcefinder/utils.py
- API docs using autoapi, theme: Furo
- also fix oldest supported test env
Doesn't really need to be addressed in this PR, can be done gradually later; many of the docstrings have formatting that isn't standard.  Basically it should conform to [`numpydoc` format](https://numpydoc.readthedocs.io/en/latest/format.html).
> Build API docs w/ Sphinx and autoapi

- sourcefinder/utils.py
Minimal change to address https://github.com/transientskp/pyse/issues/159
> Do not force the numba threading layer

- .github/workflows/python-tests.yml
- sourcefinder/utility/cli.py
- test/test_scripts/test_pyse.py
Restore consistency in use of hyphens instead of underscores for command line arguments.
> Restore consistency in use of hyphens
